#!/usr/bin/env ts-node
/**
 * sync-hints.ts
 *
 * Realm manifests (`realms/<realm>/manifest.json`) are the single source of truth for
 * progressive hint content. The flag-oracle, however, builds from its own context and
 * cannot read the manifests at runtime. This script extracts each realm's `hints` and
 * generates a bundled data module the oracle imports:
 *
 *   flag-oracle/src/config/hints-data.generated.ts
 *
 * Run after editing any manifest's hints:  npx ts-node scripts/sync-hints.ts
 */

import * as fs from 'fs';
import * as path from 'path';

const REPO_ROOT = path.resolve(__dirname, '..');
const REALMS_DIR = path.join(REPO_ROOT, 'realms');
const OUTPUT = path.join(
  REPO_ROOT,
  'flag-oracle',
  'src',
  'config',
  'hints-data.generated.ts'
);

interface ManifestHint {
  order: number;
  text: string;
}

function loadRealmHints(): Record<string, ManifestHint[]> {
  const result: Record<string, ManifestHint[]> = {};
  const entries = fs
    .readdirSync(REALMS_DIR, { withFileTypes: true })
    .filter((d) => d.isDirectory());

  for (const dir of entries) {
    const manifestPath = path.join(REALMS_DIR, dir.name, 'manifest.json');
    if (!fs.existsSync(manifestPath)) continue;

    const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf-8'));
    if (!Array.isArray(manifest.hints) || manifest.hints.length === 0) continue;

    const realm = String(manifest.realm || dir.name).toUpperCase();
    const hints: ManifestHint[] = manifest.hints
      .map((h: ManifestHint) => ({ order: Number(h.order), text: String(h.text) }))
      .sort((a: ManifestHint, b: ManifestHint) => a.order - b.order);

    result[realm] = hints;
  }

  return result;
}

function generate(): void {
  const hints = loadRealmHints();
  const realmCount = Object.keys(hints).length;

  const banner = `/**
 * AUTO-GENERATED by scripts/sync-hints.ts — DO NOT EDIT BY HAND.
 * Source of truth: realms/<realm>/manifest.json ("hints" array).
 * Regenerate with: npx ts-node scripts/sync-hints.ts
 */`;

  const body = `${banner}

export interface RealmHint {
  order: number;
  text: string;
}

export const REALM_HINTS: Record<string, RealmHint[]> = ${JSON.stringify(hints, null, 2)};
`;

  fs.writeFileSync(OUTPUT, body, 'utf-8');
  console.info(`✅ Synced hints for ${realmCount} realms → ${path.relative(REPO_ROOT, OUTPUT)}`);
}

generate();
