/**
 * AUTO-GENERATED by scripts/sync-hints.ts — DO NOT EDIT BY HAND.
 * Source of truth: realms/<realm>/manifest.json ("hints" array).
 * Regenerate with: npx ts-node scripts/sync-hints.ts
 */

export interface RealmHint {
  order: number;
  text: string;
}

export const REALM_HINTS: Record<string, RealmHint[]> = {
  "ALFHEIM": [
    {
      "order": 1,
      "text": "Cloud realms leak when misconfigured. Look for exposed settings, headers, or forgotten endpoints."
    },
    {
      "order": 2,
      "text": "Default credentials, verbose error output, or open admin/debug routes are your way in."
    },
    {
      "order": 3,
      "text": "Leverage the misconfiguration (e.g. an exposed config or debug route) to reach the flag."
    }
  ],
  "ASGARD": [
    {
      "order": 1,
      "text": "Not every door checks your badge. Enumerate endpoints and object identifiers carefully."
    },
    {
      "order": 2,
      "text": "Try reaching other users' resources or admin-only routes directly (IDOR / forced browsing)."
    },
    {
      "order": 3,
      "text": "Escalate through the broken access control to reach the privileged flag."
    }
  ],
  "HELHEIM": [
    {
      "order": 1,
      "text": "Administrative actions are not always protected as well as they should be. Hunt for an admin area."
    },
    {
      "order": 2,
      "text": "The memorial forum's admin panel trusts the client to declare who is an admin. Inspect that decision."
    },
    {
      "order": 3,
      "text": "These privileged actions are never logged or alerted on — abuse the silent admin access to reach the flag."
    }
  ],
  "JOTUNHEIM": [
    {
      "order": 1,
      "text": "Authentication here is weaker than it appears. Examine the login flow and how sessions are issued."
    },
    {
      "order": 2,
      "text": "Tokens or session identifiers may be predictable, unsigned, or improperly validated."
    },
    {
      "order": 3,
      "text": "Forge or reuse credentials to assume a privileged identity, then claim the flag."
    }
  ],
  "MIDGARD": [
    {
      "order": 1,
      "text": "The marketplace pulls in third-party packages. Ask yourself where those packages come from."
    },
    {
      "order": 2,
      "text": "A dependency is resolved from a registry whose contents an attacker can influence."
    },
    {
      "order": 3,
      "text": "Publish or substitute a malicious package version to execute code and surface the flag."
    }
  ],
  "MUSPELHEIM": [
    {
      "order": 1,
      "text": "Some flaws are not bugs — they are the design itself. Map out the full trading workflow first."
    },
    {
      "order": 2,
      "text": "A logic or race-condition flaw in the trading post lets you do something the design never intended."
    },
    {
      "order": 3,
      "text": "Exploit the business-logic gap (think timing / concurrent requests) to obtain the flag."
    }
  ],
  "NIDAVELLIR": [
    {
      "order": 1,
      "text": "User input reaches the mine database directly. Which characters can change a query’s meaning?"
    },
    {
      "order": 2,
      "text": "The search endpoint concatenates raw input into SQL. Try classic injection payloads."
    },
    {
      "order": 3,
      "text": "Use a UNION-based or boolean-based injection to read the flag straight from the database."
    }
  ],
  "NIFLHEIM": [
    {
      "order": 1,
      "text": "Every system has limits. What happens when you push a value far beyond its expected operating range?"
    },
    {
      "order": 2,
      "text": "The pressure regulation endpoint accepts numeric input without proper bounds checking. Feed it extreme values."
    },
    {
      "order": 3,
      "text": "A forced crash generates a downloadable crash report — the flag is buried in its diagnostic data."
    }
  ],
  "SVARTALFHEIM": [
    {
      "order": 1,
      "text": "The forge accepts artifacts from outside. Does it verify they have not been tampered with?"
    },
    {
      "order": 2,
      "text": "Study how updates or serialized data are validated (or not) before being trusted and executed."
    },
    {
      "order": 3,
      "text": "Craft a payload that slips past the missing integrity check to retrieve the flag."
    }
  ],
  "VANAHEIM": [
    {
      "order": 1,
      "text": "The merchants protect their secrets with cryptography — but is it strong cryptography?"
    },
    {
      "order": 2,
      "text": "Weak algorithms, hardcoded keys, or predictable IVs may let you decrypt the protected data."
    },
    {
      "order": 3,
      "text": "Break or bypass the weak cryptography to recover the flag."
    }
  ]
};
